@host = http://localhost/netflix/server
#@host = https://netflix.cristiancarrino.com

### login

POST {{host}}/user/login.php HTTP/1.1
Content-Type: application/json

{
  "username": "cris",
  "password": "cris"
}

### edit user

POST {{host}}/user/edit.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6
# NB: tutti i campi sono facoltativi
# Mettere solo quelli che si vogliono modificare

{
  "username": "cris",
  "password": "cris",
  "firstname": "Cristian",
  "lastname": "Carrino",
  "photo_url": "https://www.ausmanre.it/wp-content/uploads/2020/05/avatar.jpg",
  "birthdate": "1985-06-27"
}

### favorite films

POST {{host}}/user/favorite-films.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "ids": "1,2,3"
}

### favorite actors

POST {{host}}/user/favorite-actors.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "ids": "4,5,6"
}

### favorite genres

POST {{host}}/user/favorite-genres.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "ids": "7,8,9"
}

### film list

GET {{host}}/film/read.php HTTP/1.1
Content-Type: application/json

### add film

POST {{host}}/film/create.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "title": "Prova rest",
  "description": "Description",
  "plot": "Plot",
  "director": "Director",
  "duration": "34:78",
  "vote": 4.5,
  "release_year": 1985,
  "cover_url": "https://www.ausmanre.it/wp-content/uploads/2020/05/avatar.jpg",
  "tags": "tag1, tag2, tag3",
  "actors": [{"id": 1}, {"id": 17}, {"id": 20}],
  "genres": [{"id": 6}, {"id": 10}, {"id": 12}]
}


### edit film

POST {{host}}/film/update.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "id": 98,
  "title": "Provaaaaaaaaaaa rest",
  "description": "Description",
  "plot": "Plot",
  "director": "Director",
  "duration": "34:78",
  "vote": 4.5,
  "release_year": 1985,
  "cover_url": "https://www.ausmanre.it/wp-content/uploads/2020/05/avatar.jpg",
  "tags": "tag1, tag2, tag3",
  "actors": [{"id": 1}],
  "genres": [{"id": 6}]
}

### remove film

POST {{host}}/film/delete.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "id": 98
}

### actor list

GET {{host}}/actor/read.php HTTP/1.1
Content-Type: application/json

### actor add

POST {{host}}/actor/create.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "firstname": "Gigio",
  "lastname": "Donnarumma",
  "photo_url": "https://www.ausmanre.it/wp-content/uploads/2020/05/avatar.jpg",
  "birthdate": "1982-11-12"
}

### actor edit

POST {{host}}/actor/update.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "id": 122,
  "firstname": "Christian",
  "lastname": "De Sica",
  "photo_url": "https://www.ausmanre.it/wp-content/uploads/2020/05/avatar.jpg",
  "birthdate": "1982-11-12"
}

### actor remove

POST {{host}}/actor/delete.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "id": 122
}

### genre list

GET {{host}}/genre/read.php HTTP/1.1
Content-Type: application/json

### genre add

POST {{host}}/genre/create.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "name": "Zanzibar",
  "image_url": "https://www.ausmanre.it/wp-content/uploads/2020/05/avatar.jpg"
}

### genre edit

POST {{host}}/genre/update.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "id": 29,
  "name": "Miao",
  "image_url": "---"
}

### genre remove

POST {{host}}/genre/delete.php HTTP/1.1
Content-Type: application/json
Authorization: 28d66a4bc37586b6

{
  "id": 29
}